sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
  - bash install.sh
script:
  - source env.sh && npm run test
notifications:
  slack: devops-training-spb:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  app: damp-inlet-58780
  provider: heroku
  api_key:
    secure: 148bc493-c0cb-4988-b120-170d8971b4ae
